name: 'build images'
on: push


jobs:
  docker_buildx:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Duplicate
        uses: fkirc/skip-duplicate-actions@master
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./cmd/s3driver/Dockerfile.full
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tuomasv/csi-rclone:latest
